sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t mrnicegyu11/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mrnicegyu11/docker-react npm run test